name: download dart android sdk

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  fetch-code-upload-releases:
    runs-on: ${{matrix.os}}
    if: contains(github.ref, 'tags')
    defaults:
      run:
        shell: bash    
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
          - os: 'ubuntu-latest'
            label: 'linux'
          - os: 'macos-latest'
            label: 'macos'
          - os: 'windows-latest'
            label: 'windows'
    steps:
      - uses: actions/checkout@v1

      - name: prepare environment
        run: |
          # https://stackoverflow.com/questions/55940544/getting-user-config-git-attributes-permission-denied-but-git-doesnt-exis
          sudo chown -R $USER:$USER ~/.config
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          # https://help.github.com/en/actions/reference/development-tools-for-github-actions#add-a-system-path-add-path
          # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          # echo "::add-path::$PWD/depot_tools"
          echo "$PWD/depot_tools" >> $GITHUB_PATH

      - name: fetch dart-sdk
        run: |
          mkdir dart-sdk
          cd dart-sdk
          fetch dart > /dev/null

      - name: sync android specific code
        run: |
          cd dart-sdk
          cat .gclient
          # https://github.com/dart-lang/sdk/wiki/Building-Dart-SDK-for-Android
          echo target_os = [\'android\'] >> .gclient
          cat .gclient
          gclient sync > /dev/null

      - name: borrow some /mnt space for compress sdk source
        run: |
          pwd
          sudo mkdir /mnt/out
          sudo chown -R $USER:$USER /mnt/out
          ln -s /mnt/out out
          du -sh out/*

      - name: prepare upload assets
        run: |
          7z a out/depot_tools-${{matrix.label}}.7z depot_tools
          7z -v1g a out/dart-sdk-${{matrix.label}}.7z dart-sdk

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          file: out/depot_tools-${{matrix.label}}.7z;out/dart-sdk-${{matrix.label}}.7z*
          tags: true
          draft: false
