name: build dart android sdk

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    # https://github.community/t5/GitHub-Actions/run-step-on-if-branch-tag-is/td-p/38874
    # check whether the push is tags
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v1

      - name: prepare environment
        run: |
          # https://stackoverflow.com/questions/55940544/getting-user-config-git-attributes-permission-denied-but-git-doesnt-exis
          sudo chown -R $USER:$USER ~/.config
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          # https://help.github.com/en/actions/reference/development-tools-for-github-actions#add-a-system-path-add-path
          # echo "::add-path::$PWD/depot_tools"
          echo "$PWD/depot_tools" >> $GITHUB_PATH

      - name: install cross-compiling tools
        run: |
          # https://github.com/dart-lang/sdk/wiki/Building
          sudo apt-get update -y
          sudo apt-get install -y g++-arm-linux-gnueabihf  # For 32-bit ARM (ARMv7)
          sudo apt-get install -y g++-aarch64-linux-gnu    # For 64-bit ARM
          sudo apt-get install -y g++-multilib python curl

      - name: fetch dart-sdk
        run: |
          mkdir dart-sdk
          cd dart-sdk
          fetch dart > /dev/null

      - name: sync android specific code
        run: |
          cd dart-sdk
          cat .gclient
          # https://github.com/dart-lang/sdk/wiki/Building-Dart-SDK-for-Android
          echo target_os = [\'android\'] >> .gclient
          cat .gclient
          gclient sync > /dev/null

      - name: borrow some /mnt space for building
        run: |
          cd dart-sdk/sdk
          sudo mkdir /mnt/out
          sudo chown -R $USER:$USER /mnt/out
          ln -s /mnt/out out
          df -h

      - name: build android
        run: |
          cd dart-sdk/sdk
          # https://github.com/dart-lang/sdk/wiki/Building#building
          # Build the 64-bit SDK:
          tools/build.py --no-goma --mode release --arch x64 create_sdk | tee log.txt
          # Build the 32-bit SDK:
          tools/build.py --no-goma --mode release --arch ia32 create_sdk | tee log.txt
          # https://github.com/dart-lang/sdk/wiki/Building-the-Dart-VM-for-Android#building-for-android
          tools/build.py --no-goma --arch=arm,arm64,ia32,x64 --os=android create_sdk | tee log.txt

      - name: check the out files step 1
        run: |
          cd dart-sdk/sdk
          ls -lR .

      - name: check the out files step 2
        run: |
          cd dart-sdk/sdk
          sudo apt install -y tree
          tree 

      - name: prepare prebuilt files
        run: |
          cd dart-sdk/sdk
          # release mode
          cp -r out/ReleaseAndroidARM/dart-sdk android-arm-dart-sdk
          cp -r out/ReleaseAndroidARM64/dart-sdk android-arm64-dart-sdk 
          cp -r out/ReleaseAndroidIA32/dart-sdk android-ia32-dart-sdk
          cp -r out/ReleaseAndroidX64/dart-sdk android-x64-dart-sdk
          tar -cJf android-arm-dart-sdk.tar.xz android-arm-dart-sdk
          tar -cJf android-arm64-dart-sdk.tar.xz android-arm64-dart-sdk 
          tar -cJf android-ia32-dart-sdk.tar.xz android-ia32-dart-sdk
          tar -cJf android-x64-dart-sdk.tar.xz android-x64-dart-sdk
          # debug mode
          cp -r out/DebugAndroidARM/dart-sdk android-arm-dart-sdk-debug
          cp -r out/DebugAndroidARM64/dart-sdk android-arm64-dart-sdk-debug 
          cp -r out/DebugAndroidIA32/dart-sdk android-ia32-dart-sdk-debug
          cp -r out/DebugAndroidX64/dart-sdk android-x64-dart-sdk-debug
          tar -cJf android-arm-dart-sdk-debug.tar.xz android-arm-dart-sdk-debug
          tar -cJf android-arm64-dart-sdk-debug.tar.xz android-arm64-dart-sdk-debug 
          tar -cJf android-ia32-dart-sdk-debug.tar.xz android-ia32-dart-sdk-debug
          tar -cJf android-x64-dart-sdk-debug.tar.xz android-x64-dart-sdk-debug
          # product mode
          cp -r out/ProductAndroidARM/dart-sdk android-arm-dart-sdk-product
          cp -r out/ProductAndroidARM64/dart-sdk android-arm64-dart-sdk-product
          cp -r out/ProductAndroidIA32/dart-sdk android-ia32-dart-sdk-product
          cp -r out/ProductAndroidX64/dart-sdk android-x64-dart-sdk-product
          tar -cJf android-arm-dart-sdk-product.tar.xz android-arm-dart-sdk-product
          tar -cJf android-arm64-dart-sdk-product.tar.xz android-arm64-dart-sdk-product 
          tar -cJf android-ia32-dart-sdk-product.tar.xz android-ia32-dart-sdk-product
          tar -cJf android-x64-dart-sdk-product.tar.xz android-x64-dart-sdk-product

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          file: dart-sdk/sdk/log.txt;dart-sdk/sdk/*-dart-sdk.tar.xz;dart-sdk/sdk/*-dart-sdk-debug.tar.xz;dart-sdk/sdk/*-dart-sdk-product.tar.xz
          tags: true
          draft: false
