name: fetch-code-upload-releases

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  fetch-code-upload-releases:
    runs-on: ${{matrix.os}}
    if: contains(github.ref, 'tags')
    defaults:
      run:
        shell: bash    
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
          - os: 'ubuntu-latest'
            label: 'linux'
          - os: 'macos-latest'
            label: 'macos'
          - os: 'windows-latest'
            label: 'windows'
    steps:
      - uses: actions/checkout@v1

      - name: prepare environment
        run: |
          # https://stackoverflow.com/questions/55940544/getting-user-config-git-attributes-permission-denied-but-git-doesnt-exis
          # https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os
          if [ "$RUNNER_OS" == "Linux" ]; then
            id
            sudo chown -R $USER ~/.config
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          elif [ "$RUNNER_OS" == "macOS" ]; then
            id
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
            echo ok
          else
            echo ok
            choco install wget
            # https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_get_depot_tools
            wget https://storage.googleapis.com/chrome-infra/depot_tools.zip
            unzip depot_tools.zip -d depot_tools || true
          fi
          # https://help.github.com/en/actions/reference/development-tools-for-github-actions#add-a-system-path-add-path
          # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          # echo "::add-path::$PWD/depot_tools"
          # echo "$PWD/depot_tools" >> $GITHUB_PATH

      - name: add depot_tools to path
        run: |
          echo "$PWD/depot_tools" >> $GITHUB_PATH
          echo $GITHUB_PATH
          cat $GITHUB_PATH

      - name: add depot_tools to path on windows 
        if: matrix.os == 'windows-latest'
        run: |
          echo %CD%\depot_tools>> %GITHUB_PATH%
          echo %GITHUB_PATH%
          cat %GITHUB_PATH%
        shell: cmd

      - name: fetch dart-sdk
        if: matrix.os != 'windows-latest'
        run: |
          echo $PATH
          mkdir dart-sdk
          cd dart-sdk
          fetch dart > /dev/null

      - name: fetch dart-sdk
        if: matrix.os == 'windows-latest'
        run: |
          echo %PATH%
          set DEPOT_TOOLS_WIN_TOOLCHAIN=0
          set vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          where python
          call python -V
          call gclient
          mkdir dart-sdk
          cd dart-sdk
          call fetch dart
        shell: cmd

      - name: set target_os android
        run: |
          cat .gclient
          # https://github.com/dart-lang/sdk/wiki/Building-Dart-SDK-for-Android
          echo target_os = [\'android\'] >> .gclient
          cat .gclient
        working-directory: dart-sdk

      - name: sync code
        if: matrix.os == 'windows-latest'
        run: |
          echo %PATH%
          set DEPOT_TOOLS_WIN_TOOLCHAIN=0
          set vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          where python
          call python -V
          call gclient sync
        shell: cmd
        working-directory: dart-sdk

      - name: sync code
        if: matrix.os != 'windows-latest'
        run: |
          echo $PATH
          which python
          python -V
          gclient sync > /dev/null
        working-directory: dart-sdk

      # - name: borrow some /mnt space for compress sdk source
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     pwd
      #     ls -l
      #     df -h
      #     sudo mkdir /mnt/out
      #     sudo chown -R $USER /mnt/out
      #     ln -s /mnt/out out
      #     du -sh *

      # - name: borrow some /mnt space for compress sdk source
      #   if: matrix.os != 'ubuntu-latest'
      #   run: |
      #     pwd
      #     ls -l
      #     df -h
      #     mkdir out
      #     du -sh *

      - name: prepare
        run: |
          pwd
          ls -l
          df -h
          mkdir out
          du -sh *

      - name: prepare upload assets
        run: |
          7z a out/depot_tools-${{matrix.label}}.7z depot_tools
          7z -v1g a out/dart-sdk-${{matrix.label}}.7z dart-sdk

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          file: out/depot_tools-${{matrix.label}}.7z;out/dart-sdk-${{matrix.label}}.7z*
          tags: true
          draft: false
